spring:
  cloud:
    stream:
      bindings:
        output:
          destination: friend
          contentType: 'application/json'
  profiles:
    active: development
server:
  port: ${PORT:${SERVER_PORT:8100}}
logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.neo4j.*: INFO
    com.memorynotfound: DEBUG
    org.apache.kafka.*: WARN
    liquibase.integration.spring.SpringLiquibase: ERROR
---
postgres.port: 5432
postgres.host: localhost
postgres.url: jdbc:postgresql://${postgres.host:localhost}:${postgres.port}/${postgres.database-name}
postgres.database-name: postgres
spring:
  profiles: development
  datasource:
    url: ${postgres.url}
    data-username: user
    data-password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: ${postgres.url}
    user: user
    password: postgres
    enabled: false
  cloud:
    kubernetes.discovery.enabled: false
    kubernetes.ribbon.enabled: false
    kubernetes.enabled: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
postgres.port: 5432
postgres.host: friend-db
postgres.url: jdbc:postgresql://${postgres.host:localhost}:${postgres.port}/${postgres.database-name}
postgres.database-name: postgres
spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          defaultBrokerPort: 29092
          zkNodes: zookeeper
          defaultZkPort: 32181
    kubernetes.discovery.enabled: false
    kubernetes.ribbon.enabled: false
    kubernetes.enabled: false
  datasource:
    url: ${postgres.url}
    data-username: postgres
    data-password: example
    driver-class-name: org.postgresql.Driver
    xa:
      data-source-class-name: org.postgresql.xa.PGXADataSource
  liquibase:
    url: ${postgres.url}
    user: postgres
    password: example
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
postgres.port: 5432
postgres.host: friend-db
postgres.database-name: postgres
postgres.url: jdbc:postgresql://${postgres.host:localhost}:${postgres.port}/${postgres.database-name}
postgres.password: example
postgres.username: postgres
spring:
  profiles: kubernetes
  cloud:
    stream:
      kafka:
        binder:
          brokers: "PLAINTEXT://social-network-kafka:9092"
  datasource:
    url: ${postgres.url}
    data-username: postgres
    data-password: example
    driver-class-name: org.postgresql.Driver
    xa:
      data-source-class-name: org.postgresql.xa.PGXADataSource
  liquibase:
    url: ${postgres.url}
    user: ${postgres.username}
    password: ${postgres.password}
ribbon.eureka.enabled: false
eureka.client.enabled: false
---
postgres.port: 5432
postgres.host: localhost
postgres.url: ${spring.datasource.url}
postgres.database-name: postgres
spring:
  profiles: test
  cloud:
    kubernetes.discovery.enabled: false
    kubernetes.ribbon.enabled: false
    kubernetes.enabled: false
  datasource:
    url: jdbc:postgresql://${postgres.host:localhost}:${postgres.port}/${postgres.database-name}
    data-username: postgres
    data-password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    url:
    user: postgres
    password: password
    enabled: true
eureka:
  client:
    enabled: false
management:
  metrics:
    export:
      prometheus:
        enabled: false