spring:
  application:
    name: recommendation-service
  cloud:
    stream:
      bindings:
        user:
          destination: user
          group: user-group
          contentType: 'application/json'
          consumer:
            durableSubscription: false
            concurrency: 5
            instanceIndex: 1
        friend:
          destination: friend
          group: friend-group
          contentType: 'application/json'
          consumer:
            durableSubscription: false
            concurrency: 5
            instanceIndex: 1
  profiles:
    active: docker
server:
  port: ${PORT:${SERVER_PORT:0}}
---
spring:
  profiles: development
  data:
    neo4j:
      uri: "http://localhost:7474/"
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  data:
    neo4j:
      uri: "http://neo4j:7474/"
  cloud:
    stream:
      kafka:
        binder:
          brokers: "kafka:29092"
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  data:
    neo4j:
      uri: "file:///var/tmp/neo4j-test.db"