spring:
  cloud:
    stream:
      bindings:
        user:
          destination: user
          group: user-group
          contentType: 'application/json'
          consumer:
            durableSubscription: false
            concurrency: 1
            instanceIndex: 1
        friend:
          destination: friend
          group: friend-group
          contentType: 'application/json'
          consumer:
            durableSubscription: false
            concurrency: 1
            instanceIndex: 1
  profiles:
    active: development
server:
  port: ${PORT:${SERVER_PORT:8110}}
logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.apache.kafka.*: WARN
---
spring:
  profiles: development
  data:
    neo4j:
      uri: "bolt://localhost:7687"
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"
    kubernetes.discovery.enabled: false
    kubernetes.ribbon.enabled: false
    kubernetes.enabled: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  data:
    neo4j:
      uri: "bolt://neo4j:7687"
  cloud:
    stream:
      kafka:
        binder:
          brokers: "kafka:29092"
    kubernetes.discovery.enabled: false
    kubernetes.ribbon.enabled: false
    kubernetes.enabled: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: kubernetes
  data:
    neo4j:
      uri: "bolt://social-network-neo4j:7687"
  cloud:
    kubernetes.discovery.enabled: true
    kubernetes.ribbon.enabled: true
    kubernetes.enabled: true
    stream:
      kafka:
        binder:
          brokers: "PLAINTEXT://social-network-kafka:9092"
ribbon.eureka.enabled: false
eureka.client.enabled: false
---
spring:
  profiles: test
  cloud:
    kubernetes.discovery.enabled: false
    kubernetes.ribbon.enabled: false
    kubernetes.enabled: false
  data:
    neo4j:
      embedded:
        enabled: true
management:
  metrics:
    export:
      prometheus:
        enabled: false