spring:
  profiles:
    active: development
  application:
    name: discovery-service
server:
  port: 8761
logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.neo4j.*: INFO
    com.memorynotfound: DEBUG
    org.apache.kafka.*: ERROR
---
spring:
  config.activate.on-profile: development
  cloud:
    kubernetes.discovery.enabled: false
    kubernetes.ribbon.enabled: false
    kubernetes.enabled: false
eureka:
  instance:
    preferIpAddress: true
---
spring:
  config.activate.on-profile: docker
  cloud:
    kubernetes.discovery.enabled: false
    kubernetes.ribbon.enabled: false
    kubernetes.enabled: false
eureka:
  instance:
    preferIpAddress: true
---
spring:
  config.activate.on-profile: test
  cloud:
    kubernetes.discovery.enabled: false
    kubernetes.ribbon.enabled: false
    kubernetes.enabled: false
prometheus.enabled: false
eureka:
  client:
    enabled: false