version: '3'

services:

  discovery-service:
    build: .
    image: hyperskale/discovery-service:0.0.1-SNAPSHOT

  edge-service:
    build: .
    image: hyperskale/edge-service:0.0.1-SNAPSHOT

  friend-service:
    build: .
    image: hyperskale/friend-service:0.0.1-SNAPSHOT

  user-service:
    build: .
    image: hyperskale/user-service:0.0.1-SNAPSHOT

  recommendation-service:
    build: .
    image: hyperskale/recommendation-service:0.0.1-SNAPSHOT
